### ISSUE TITLE
New auto number starts at 1000

### ISSUE THREAD

**Issue by mariusagur** [rappen/AutoNumManager#4] opened 2017-10-24 08:03 UTC
**What I did:**
Created a new autonumber, set length to 100, selected {SEQNUM:1}, and updated.
**What I expected:**
When a new opportunity was created, the number would start at 0 or 1
**What happened:**
The number started at 1000
![image](https://user-images.githubusercontent.com/25456745/31931140-7d5083ec-b8a2-11e7-93e5-37cf4784e05d.png)

**Comment by rappen** [comment] 2017-10-24 08:35
Result for above screenshot should be "1".
Never seen similar behavior, can you reproduce?

**Comment by mariusagur** [comment] 2017-10-24 10:42
Yes, I've created a new field and the same issue here
![image](https://user-images.githubusercontent.com/25456745/31938750-b7ace948-b8b8-11e7-95f9-b2133693a0b3.png)
![image](https://user-images.githubusercontent.com/25456745/31938763-bd36db08-b8b8-11e7-92e1-6e96807205d9.png)

**Comment by rappen** [comment] 2017-10-24 11:09
After investigation I can reproduce the problem and cannot see any other explanation than that this is a bug in the platform, and a new one too. This behavior was not seen last week.
Currently testing org has version 9.0.0.2090.

Workaround: Set seed to 1 when creating new attribute. I will update the tool to default use 1 as seed.

**Comment by mariusagur** [comment] 2017-10-24 11:13
Are you also experiencing it? I can reset the instance (sandbox) and try again if you want to?

**Comment by rappen** [comment] 2017-10-24 11:50
Connect: https://connect.microsoft.com/DynamicsCustomerEngagement/feedback/details/3142960

**Comment by rappen** [comment] 2019-02-08 15:10
Closing as this is by design in the platform.

**Closed as completed by rappen** 2019-02-08 15:10 UTC
